if(${PLATFORM} MATCHES "aarch64")
    set(CMAKE_C_COMPILER $ENV{ARM_TOOLCHAIN}/bin/aarch64-none-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER $ENV{ARM_TOOLCHAIN}/bin/aarch64-none-linux-gnu-g++)
    set(CMAKE_ASM_COMPILER $ENV{ARM_TOOLCHAIN}/bin/aarch64-none-linux-gnu-gcc)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mcpu=${MCPU}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mcpu=${MCPU}")
elseif(${PLATFORM} MATCHES "riscv64")
    if("$ENV{SOC_CROSS_MODE}" STREQUAL "ON")
        set(CMAKE_C_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-g++)
        set(CMAKE_ASM_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-gcc)
    else()
        set(CMAKE_C_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-linux-gnu-g++)
        set(CMAKE_ASM_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-linux-gnu-gcc)
    endif()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
elseif(${PLATFORM} MATCHES "x86_64")
    message(STATUS "platform is x86_64, and use the default compiler toolchain")
else()
    message(STATUS "Variable platform is not defined")
endif()
