set(prebuilt_path ${CMAKE_SOURCE_DIR}/../bm_prebuilt_toolchains_win)
if (NOT EXISTS ${prebuilt_path})
    set(prebuilt_path ${CMAKE_SOURCE_DIR}/../bm_prebuilt_toolchains)
endif()
if (NOT EXISTS ${prebuilt_path})
    set(prebuilt_path ${CMAKE_SOURCE_DIR}/../../bm_prebuilt_toolchains)
endif()
set(CMAKE_C_COMPILER ${prebuilt_path}/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc)
set(CMAKE_CXX_COMPILER ${prebuilt_path}/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/aarch64-none-elf-g++)
