#ifndef __GDE_REG_DEF_H__
#define __GDE_REG_DEF_H__


// gde reg id defines
#define GDE_ID_PIO_ENABLE                       {0,   1}
#define GDE_ID_INT_ENABLE                       {1,   1}
#define GDE_ID_RESERVED0                        {2,   6}
#define GDE_ID_ENGINE_BUSY                      {8,   1}
#define GDE_ID_QOS                              {9,   3}
#define GDE_ID_RESERVED1                        {12, 20}
#define GDE_ID_DSCRP_START                      {32,  1}
#define GDE_ID_RESERVED2                        {33,  3}
#define GDE_ID_DSCRP_START_ADDR_31_4            {36, 28}
#define GDE_ID_DSCRP_START_ADDR_63_32           {64, 32}
#define GDE_ID_OP_SYNC_ID_FINISH                {96, 32}
#define GDE_ID_PIO_BUF_DEPTH                    {128, 4}
#define GDE_ID_RESERVED3                        {132, 28}
#define GDE_ID_DSCRP_INT_STS                    {160, 1}
#define GDE_ID_RESERVED4                        {161, 31}
#define GDE_ID_REG_SYNC_ID_SW_CLR               {192, 1}
#define GDE_ID_RESERVED5                        {193, 31}
#define GDE_ID_RESERVED6                        {224, 32}
#define GDE_ID_REG_SYNC_ID0                     {256, 32}
#define GDE_ID_REG_SYNC_ID1                     {288, 32}
#define GDE_ID_REG_SYNC_ID2                     {320, 32}
#define GDE_ID_REG_SYNC_ID3                     {352, 32}
#define GDE_ID_REG_SYNC_ID4                     {384, 32}
#define GDE_ID_REG_SYNC_ID5                     {416, 32}
#define GDE_ID_REG_SYNC_ID6                     {448, 32}
#define GDE_ID_REG_SYNC_ID7                     {480, 32}
#define GDE_ID_DSCP_VLD                         {512, 1}
#define GDE_ID_RESERVED7                        {513, 7}
#define GDE_ID_ENABLE_SYNCID                    {520, 1}
#define GDE_ID_RESERVED8                        {521, 7}
#define GDE_ID_INT_STS_EN                       {528, 1}
#define GDE_ID_RESERVED9                        {529, 7}
#define GDE_ID_EOD                              {536, 1}
#define GDE_ID_RESERVED10                       {537, 7}
#define GDE_ID_OP_SYNC_ID                       {544, 32}
#define GDE_ID_EXP_SYNC_ID_0                    {576, 32}
#define GDE_ID_EXP_SYNC_ID_1                    {608, 32}
#define GDE_ID_EXP_SYNC_ID_2                    {640, 32}
#define GDE_ID_EXP_SYNC_ID_3                    {672, 32}
#define GDE_ID_EXP_SYNC_ID_4                    {704, 32}
#define GDE_ID_EXP_SYNC_ID_5                    {736, 32}
#define GDE_ID_EXP_SYNC_ID_6                    {768, 32}
#define GDE_ID_EXP_SYNC_ID_7                    {800, 32}
#define GDE_ID_RESERVED11                       {832, 6}
#define GDE_ID_GDE_IDAR_L                       {838, 26}
#define GDE_ID_GDE_IDAR_H                       {864, 32}
#define GDE_ID_RESERVED12                       {896, 6}
#define GDE_ID_GDE_PDAR_L                       {902, 26}
#define GDE_ID_GDE_PDAR_H                       {928, 32}
#define GDE_ID_RESERVED13                       {960, 6}
#define GDE_ID_GDE_IDXAR_L                      {966, 26}
#define GDE_ID_GDE_IDXAR_H                      {992, 32}
#define GDE_ID_SRC_HSIZE                        {1024, 32}
#define GDE_ID_SRC_WSIZE                        {1056, 32}
#define GDE_ID_SRC_DATA_FORMAT                  {1088, 32}
#define GDE_ID_INDEX_SIZE                       {1120, 32}
#define GDE_ID_GDE_TABLE_SIDX                   {1152, 32}
#define GDE_ID_GDE_TABLE_EIDX                   {1184, 32}
#define GDE_ID_ENABLE_FILL_CONSANT              {1216, 32}
#define GDE_ID_CONSTANT_VALUE                   {1248, 32}


// gde pack defines
#define GDE_PACK_PIO_ENABLE(val)                       {GDE_ID_PIO_ENABLE, (val)}
#define GDE_PACK_INT_ENABLE(val)                       {GDE_ID_INT_ENABLE, (val)}
#define GDE_PACK_RESERVED0(val)                        {GDE_ID_RESERVED0, (val)}
#define GDE_PACK_ENGINE_BUSY(val)                      {GDE_ID_ENGINE_BUSY, (val)}
#define GDE_PACK_QOS(val)                              {GDE_ID_QOS, (val)}
#define GDE_PACK_RESERVED1(val)                        {GDE_ID_RESERVED1, (val)}
#define GDE_PACK_DSCRP_START(val)                      {GDE_ID_DSCRP_START, (val)}
#define GDE_PACK_RESERVED2(val)                        {GDE_ID_RESERVED2, (val)}
#define GDE_PACK_DSCRP_START_ADDR_31_4(val)            {GDE_ID_DSCRP_START_ADDR_31_4, (val)}
#define GDE_PACK_DSCRP_START_ADDR_63_32(val)           {GDE_ID_DSCRP_START_ADDR_63_32, (val)}
#define GDE_PACK_OP_SYNC_ID_FINISH(val)                {GDE_ID_OP_SYNC_ID_FINISH, (val)}
#define GDE_PACK_PIO_BUF_DEPTH(val)                    {GDE_ID_PIO_BUF_DEPTH, (val)}
#define GDE_PACK_RESERVED3(val)                        {GDE_ID_RESERVED3, (val)}
#define GDE_PACK_DSCRP_INT_STS(val)                    {GDE_ID_DSCRP_INT_STS, (val)}
#define GDE_PACK_RESERVED4(val)                        {GDE_ID_RESERVED4, (val)}
#define GDE_PACK_REG_SYNC_ID_SW_CLR(val)               {GDE_ID_REG_SYNC_ID_SW_CLR, (val)}
#define GDE_PACK_RESERVED5(val)                        {GDE_ID_RESERVED5, (val)}
#define GDE_PACK_RESERVED6(val)                        {GDE_ID_RESERVED6, (val)}
#define GDE_PACK_REG_SYNC_ID0(val)                     {GDE_ID_REG_SYNC_ID0, (val)}
#define GDE_PACK_REG_SYNC_ID1(val)                     {GDE_ID_REG_SYNC_ID1, (val)}
#define GDE_PACK_REG_SYNC_ID2(val)                     {GDE_ID_REG_SYNC_ID2, (val)}
#define GDE_PACK_REG_SYNC_ID3(val)                     {GDE_ID_REG_SYNC_ID3, (val)}
#define GDE_PACK_REG_SYNC_ID4(val)                     {GDE_ID_REG_SYNC_ID4, (val)}
#define GDE_PACK_REG_SYNC_ID5(val)                     {GDE_ID_REG_SYNC_ID5, (val)}
#define GDE_PACK_REG_SYNC_ID6(val)                     {GDE_ID_REG_SYNC_ID6, (val)}
#define GDE_PACK_REG_SYNC_ID7(val)                     {GDE_ID_REG_SYNC_ID7, (val)}
#define GDE_PACK_DSCP_VLD(val)                         {GDE_ID_DSCP_VLD, (val)}
#define GDE_PACK_RESERVED7(val)                        {GDE_ID_RESERVED7, (val)}
#define GDE_PACK_ENABLE_SYNCID(val)                    {GDE_ID_ENABLE_SYNCID, (val)}
#define GDE_PACK_RESERVED8(val)                        {GDE_ID_RESERVED8, (val)}
#define GDE_PACK_INT_STS_EN(val)                       {GDE_ID_INT_STS_EN, (val)}
#define GDE_PACK_RESERVED9(val)                        {GDE_ID_RESERVED9, (val)}
#define GDE_PACK_EOD(val)                              {GDE_ID_EOD, (val)}
#define GDE_PACK_RESERVED10(val)                       {GDE_ID_RESERVED10, (val)}
#define GDE_PACK_OP_SYNC_ID(val)                       {GDE_ID_OP_SYNC_ID, (val)}
#define GDE_PACK_EXP_SYNC_ID_0(val)                    {GDE_ID_EXP_SYNC_ID_0, (val)}
#define GDE_PACK_EXP_SYNC_ID_1(val)                    {GDE_ID_EXP_SYNC_ID_1, (val)}
#define GDE_PACK_EXP_SYNC_ID_2(val)                    {GDE_ID_EXP_SYNC_ID_2, (val)}
#define GDE_PACK_EXP_SYNC_ID_3(val)                    {GDE_ID_EXP_SYNC_ID_3, (val)}
#define GDE_PACK_EXP_SYNC_ID_4(val)                    {GDE_ID_EXP_SYNC_ID_4, (val)}
#define GDE_PACK_EXP_SYNC_ID_5(val)                    {GDE_ID_EXP_SYNC_ID_5, (val)}
#define GDE_PACK_EXP_SYNC_ID_6(val)                    {GDE_ID_EXP_SYNC_ID_6, (val)}
#define GDE_PACK_EXP_SYNC_ID_7(val)                    {GDE_ID_EXP_SYNC_ID_7, (val)}
#define GDE_PACK_RESERVED11(val)                       {GDE_ID_RESERVED11, (val)}
#define GDE_PACK_GDE_IDAR_L(val)                       {GDE_ID_GDE_IDAR_L, (val)}
#define GDE_PACK_GDE_IDAR_H(val)                       {GDE_ID_GDE_IDAR_H, (val)}
#define GDE_PACK_RESERVED12(val)                       {GDE_ID_RESERVED12, (val)}
#define GDE_PACK_GDE_PDAR_L(val)                       {GDE_ID_GDE_PDAR_L, (val)}
#define GDE_PACK_GDE_PDAR_H(val)                       {GDE_ID_GDE_PDAR_H, (val)}
#define GDE_PACK_RESERVED13(val)                       {GDE_ID_RESERVED13, (val)}
#define GDE_PACK_GDE_IDXAR_L(val)                      {GDE_ID_GDE_IDXAR_L, (val)}
#define GDE_PACK_GDE_IDXAR_H(val)                      {GDE_ID_GDE_IDXAR_H, (val)}
#define GDE_PACK_SRC_HSIZE(val)                        {GDE_ID_SRC_HSIZE, (val)}
#define GDE_PACK_SRC_WSIZE(val)                        {GDE_ID_SRC_WSIZE, (val)}
#define GDE_PACK_SRC_DATA_FORMAT(val)                  {GDE_ID_SRC_DATA_FORMAT, (val)}
#define GDE_PACK_INDEX_SIZE(val)                       {GDE_ID_INDEX_SIZE, (val)}
#define GDE_PACK_GDE_TABLE_SIDX(val)                   {GDE_ID_GDE_TABLE_SIDX, (val)}
#define GDE_PACK_GDE_TABLE_EIDX(val)                   {GDE_ID_GDE_TABLE_EIDX, (val)}
#define GDE_PACK_ENABLE_FILL_CONSANT(val)              {GDE_ID_ENABLE_FILL_CONSANT, (val)}
#define GDE_PACK_CONSTANT_VALUE(val)                   {GDE_ID_CONSTANT_VALUE, (val)}


#endif // __GDE_REG_DEF_H__
