#ifndef __NMS_REG_DEF_H__
#define __NMS_REG_DEF_H__


// NMS reg id defines
#define NMS_ID_RESERVED0                           {2, 30}
#define NMS_ID_INT_ENABLE                          {1, 1}
#define NMS_ID_PIO_ENABLE                          {0, 1}
#define NMS_ID_DSCRP_START_ADDR_31_2               {34, 30}
#define NMS_ID_RESERVED1                           {33, 1}
#define NMS_ID_DSCRP_START                         {32, 1}
#define NMS_ID_DSCRP_START_ADDR_63_32              {64, 32}
#define NMS_ID_OP_SYNC_ID_FINISH                   {96, 32}
#define NMS_ID_RESERVED2                           {137, 23}
#define NMS_ID_ENGINE_BUSY                         {136, 1}
#define NMS_ID_RESERVED3                           {132, 4}
#define NMS_ID_PIO_BUF_DEPTH                       {128, 4}
#define NMS_ID_RESERVED4                           {161, 31}
#define NMS_ID_DSCRP_INT_STS                       {160, 1}
#define NMS_ID_RESERVED5                           {193, 31}
#define NMS_ID_REG_SYNC_ID_SW_CLR                  {192, 1}
#define NMS_ID_RESERVED6                           {224, 32}
#define NMS_ID_REG_SYNC_ID_31_0                    {256, 32}
#define NMS_ID_REG_SYNC_ID_63_32                   {288, 32}
#define NMS_ID_REG_SYNC_ID_95_64                   {320, 32}
#define NMS_ID_REG_SYNC_ID_127_96                  {352, 32}
#define NMS_ID_REG_SYNC_ID_159_128                 {384, 32}
#define NMS_ID_REG_SYNC_ID_191_160                 {416, 32}
#define NMS_ID_REG_SYNC_ID_223_192                 {448, 32}
#define NMS_ID_REG_SYNC_ID_255_224                 {480, 32}
#define NMS_ID_RESERVED7                           {537, 7}
#define NMS_ID_EOD                                 {536, 1}
#define NMS_ID_RESERVED8                           {529, 7}
#define NMS_ID_INT_STS_EN                          {528, 1}
#define NMS_ID_RESERVED9                           {521, 7}
#define NMS_ID_ENABLE_SYNCID                       {520, 1}
#define NMS_ID_RESERVED10                          {513, 7}
#define NMS_ID_DSCP_VLD                            {512, 1}
#define NMS_ID_OP_SYNC_ID                          {544, 32}
#define NMS_ID_EXP_SYNC_ID_0                       {576, 32}
#define NMS_ID_EXP_SYNC_ID_1                       {608, 32}
#define NMS_ID_EXP_SYNC_ID_2                       {640, 32}
#define NMS_ID_EXP_SYNC_ID_3                       {672, 32}
#define NMS_ID_EXP_SYNC_ID_4                       {704, 32}
#define NMS_ID_EXP_SYNC_ID_5                       {736, 32}
#define NMS_ID_EXP_SYNC_ID_6                       {768, 32}
#define NMS_ID_EXP_SYNC_ID_7                       {800, 32}
#define NMS_ID_NMS_MODE_SEL                        {863, 1}
#define NMS_ID_RESERVED11                          {856, 7}
#define NMS_ID_PRE_NMS_PP_START_ADDR_39_32         {848, 8}
#define NMS_ID_POST_NMS_PP_NUMBER_15_0              {832, 16}
#define NMS_ID_PRE_NMS_PP_START_ADDR_31_0          {864, 32}
#define NMS_ID_SOFT_NMS_THRESHOLD                  {896, 32}
#define NMS_ID_PRE_NMS_PP_NUMBER_15_0              {944, 16}
#define NMS_ID_SCORE_START_ADDR_39_32              {936, 8}
#define NMS_ID_POST_PP_BITMAP_START_ADDR_39_32     {928, 8}
#define NMS_ID_SCORE_START_ADDR_31_0               {960, 32}
#define NMS_ID_POST_PP_BITMAP_START_ADDR_31_0      {992, 32}
#define NMS_ID_RESERVED12                          {1048, 8}
#define NMS_ID_POST_NMS_PP_NUMBER_23_16            {1040, 8}
#define NMS_ID_RESERVED13                          {1032, 8}
#define NMS_ID_PRE_NMS_PP_NUMBER_23_16             {1024, 8}


// NMS pack defines
#define NMS_PACK_RESERVED0(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_INT_ENABLE(val)                      {NMS_ID_INT_ENABLE, (val)}
#define NMS_PACK_PIO_ENABLE(val)                      {NMS_ID_PIO_ENABLE, (val)}
#define NMS_PACK_DSCRP_START_ADDR_31_4(val)           {NMS_ID_DSCRP_START_ADDR_31_4, (val)}
#define NMS_PACK_RESERVED1(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_DSCRP_START(val)                     {NMS_ID_DSCRP_START, (val)}
#define NMS_PACK_DSCRP_START_ADDR_63_32(val)          {NMS_ID_DSCRP_START_ADDR_63_32, (val)}
#define NMS_PACK_OP_SYNC_ID_FINISH(val)               {NMS_ID_OP_SYNC_ID_FINISH, (val)}
#define NMS_PACK_RESERVED2(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_ENGINE_BUSY(val)                     {NMS_ID_ENGINE_BUSY, (val)}
#define NMS_PACK_RESERVED3(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_PIO_BUF_DEPTH(val)                   {NMS_ID_PIO_BUF_DEPTH, (val)}
#define NMS_PACK_RESERVED4(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_DSCRP_INT_STS(val)                   {NMS_ID_DSCRP_INT_STS, (val)}
#define NMS_PACK_RESERVED5(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_REG_SYNC_ID_SW_CLR(val)              {NMS_ID_REG_SYNC_ID_SW_CLR, (val)}
#define NMS_PACK_RESERVED6(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_REG_SYNC_ID_31_0(val)                {NMS_ID_REG_SYNC_ID_31_0, (val)}
#define NMS_PACK_REG_SYNC_ID_63_32(val)               {NMS_ID_REG_SYNC_ID_63_32, (val)}
#define NMS_PACK_REG_SYNC_ID_95_64(val)               {NMS_ID_REG_SYNC_ID_95_64, (val)}
#define NMS_PACK_REG_SYNC_ID_127_96(val)              {NMS_ID_REG_SYNC_ID_127_96, (val)}
#define NMS_PACK_REG_SYNC_ID_159_128(val)             {NMS_ID_REG_SYNC_ID_159_128, (val)}
#define NMS_PACK_REG_SYNC_ID_191_160(val)             {NMS_ID_REG_SYNC_ID_191_160, (val)}
#define NMS_PACK_REG_SYNC_ID_223_192(val)             {NMS_ID_REG_SYNC_ID_223_192, (val)}
#define NMS_PACK_REG_SYNC_ID_255_224(val)             {NMS_ID_REG_SYNC_ID_255_224, (val)}
#define NMS_PACK_RESERVED7(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_EOD(val)                             {NMS_ID_EOD, (val)}
#define NMS_PACK_RESERVED8(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_INT_STS_EN(val)                      {NMS_ID_INT_STS_EN, (val)}
#define NMS_PACK_RESERVED9(val)                       {NMS_ID_RESERVED, (val)}
#define NMS_PACK_ENABLE_SYNCID(val)                   {NMS_ID_ENABLE_SYNCID, (val)}
#define NMS_PACK_RESERVED10(val)                      {NMS_ID_RESERVED, (val)}
#define NMS_PACK_DSCP_VLD(val)                        {NMS_ID_DSCP_VLD, (val)}
#define NMS_PACK_OP_SYNC_ID(val)                      {NMS_ID_OP_SYNC_ID, (val)}
#define NMS_PACK_EXP_SYNC_ID_0(val)                   {NMS_ID_EXP_SYNC_ID_0, (val)}
#define NMS_PACK_EXP_SYNC_ID_1(val)                   {NMS_ID_EXP_SYNC_ID_1, (val)}
#define NMS_PACK_EXP_SYNC_ID_2(val)                   {NMS_ID_EXP_SYNC_ID_2, (val)}
#define NMS_PACK_EXP_SYNC_ID_3(val)                   {NMS_ID_EXP_SYNC_ID_3, (val)}
#define NMS_PACK_EXP_SYNC_ID_4(val)                   {NMS_ID_EXP_SYNC_ID_4, (val)}
#define NMS_PACK_EXP_SYNC_ID_5(val)                   {NMS_ID_EXP_SYNC_ID_5, (val)}
#define NMS_PACK_EXP_SYNC_ID_6(val)                   {NMS_ID_EXP_SYNC_ID_6, (val)}
#define NMS_PACK_EXP_SYNC_ID_7(val)                   {NMS_ID_EXP_SYNC_ID_7, (val)}
#define NMS_PACK_NMS_MODE_SEL(val)                    {NMS_ID_NMS_MODE_SEL, (val)}
#define NMS_PACK_RESERVED11(val)                      {NMS_ID_RESERVED11, (val)}
#define NMS_PACK_PRE_NMS_PP_START_ADDR_39_32(val)     {NMS_ID_PRE_NMS_PP_START_ADDR_39_32, (val)}
#define NMS_PACK_POST_NMS_PP_NUMBER_15_0(val)         {NMS_ID_POST_NMS_PP_NUMBER_15_0, (val)}
#define NMS_PACK_PRE_NMS_PP_START_ADDR_31_0(val)      {NMS_ID_PRE_NMS_PP_START_ADDR_31_0, (val)}
#define NMS_PACK_SOFT_NMS_THRESHOLD(val)              {NMS_ID_SOFT_NMS_THRESHOLD, (val)}
#define NMS_PACK_PRE_NMS_PP_NUMBER_15_0(val)          {NMS_ID_PRE_NMS_PP_NUMBER_15_0, (val)}
#define NMS_PACK_SCORE_START_ADDR_39_32(val)          {NMS_ID_SCORE_START_ADDR_39_32, (val)}
#define NMS_PACK_POST_PP_BITMAP_START_ADDR_39_32(val) {NMS_ID_POST_PP_BITMAP_START_ADDR_39_32, (val)}
#define NMS_PACK_SCORE_START_ADDR_31_0(val)           {NMS_ID_SCORE_START_ADDR_31_0, (val)}
#define NMS_PACK_POST_PP_BITMAP_START_ADDR_31_0(val)  {NMS_ID_POST_PP_BITMAP_START_ADDR_31_0, (val)}
#define NMS_PACK_RESERVED12(val)                      {NMS_ID_RESERVED12, (val)}
#define NMS_PACK_POST_NMS_PP_NUMBER_23_16(val)        {NMS_ID_POST_NMS_PP_NUMBER_23_16, (val)}
#define NMS_PACK_RESERVED13(val)                      {NMS_ID_RESERVED13, (val)}
#define NMS_PACK_PRE_NMS_PP_NUMBER_23_16(val)         {NMS_ID_PRE_NMS_PP_NUMBER_23_16, (val)}


#endif  // __NMS_REG_DEF_H__
