#ifndef __SORT_REG_DEF_H__
#define __SORT_REG_DEF_H__


// sort reg id defines
#define SORT_ID_RESERVED0                         {2, 30}
#define SORT_ID_INT_ENABLE                        {1, 1}
#define SORT_ID_PIO_ENABLE                        {0, 1}
#define SORT_ID_DSCRP_START_ADDR_31_4             {36, 28}
#define SORT_ID_RESERVED1                         {33, 3}
#define SORT_ID_DSCRP_START                       {32, 1}
#define SORT_ID_DSCRP_START_ADDR_63_32            {64, 32}
#define SORT_ID_OP_SYNC_ID_FINISH                 {96, 32}
#define SORT_ID_RESERVED2                         {137, 23}
#define SORT_ID_ENGINE_BUSY                       {136, 1}
#define SORT_ID_RESERVED3                         {132, 4}
#define SORT_ID_PIO_BUF_DEPTH                     {128, 4}
#define SORT_ID_RESERVED4                         {161, 31}
#define SORT_ID_DSCRP_INT_STS                     {160, 1}
#define SORT_ID_RESERVED5                         {193, 31}
#define SORT_ID_REG_SYNC_ID_SW_CLR                {192, 1}
#define SORT_ID_RESERVED6                         {224, 32}
#define SORT_ID_REG_SYNC_ID_31_0                  {256, 32}
#define SORT_ID_REG_SYNC_ID_63_32                 {288, 32}
#define SORT_ID_REG_SYNC_ID_95_64                 {320, 32}
#define SORT_ID_REG_SYNC_ID_127_96                {352, 32}
#define SORT_ID_REG_SYNC_ID_159_128               {384, 32}
#define SORT_ID_REG_SYNC_ID_191_160               {416, 32}
#define SORT_ID_REG_SYNC_ID_223_192               {448, 32}
#define SORT_ID_REG_SYNC_ID_255_224               {480, 32}
#define SORT_ID_RESERVED7                         {537, 7}
#define SORT_ID_EOD                               {536, 1}
#define SORT_ID_RESERVED8                         {529, 7}
#define SORT_ID_INT_STS_EN                        {528, 1}
#define SORT_ID_RESERVED9                         {521, 7}
#define SORT_ID_ENABLE_SYNCID                     {520, 1}
#define SORT_ID_RESERVED10                        {513, 7}
#define SORT_ID_DSCP_VLD                          {512, 1}
#define SORT_ID_OP_SYNC_ID                        {544, 32}
#define SORT_ID_EXP_SYNC_ID_0                     {576, 32}
#define SORT_ID_EXP_SYNC_ID_1                     {608, 32}
#define SORT_ID_EXP_SYNC_ID_2                     {640, 32}
#define SORT_ID_EXP_SYNC_ID_3                     {672, 32}
#define SORT_ID_EXP_SYNC_ID_4                     {704, 32}
#define SORT_ID_EXP_SYNC_ID_5                     {736, 32}
#define SORT_ID_EXP_SYNC_ID_6                     {768, 32}
#define SORT_ID_EXP_SYNC_ID_7                     {800, 32}
#define SORT_ID_SRC_OFFSET_INDX                   {832, 32}
#define SORT_ID_SORTCNT_ADDR_31_0                 {864, 32}
#define SORT_ID_SORTCNT_ADDR_39_32                {920, 8}
#define SORT_ID_DIS_WR_DST_SORTCNT                {919, 1}
#define SORT_ID_DIS_WR_DST_SORT_DAT               {918, 1}
#define SORT_ID_DIS_WR_DST_SORT_IDX               {917, 1}
#define SORT_ID_SORT_RES_INDX_SEL                 {916, 1}
#define SORT_ID_RESERVED12                        {915, 1}
#define SORT_ID_RESERVED13                        {914, 1}
#define SORT_ID_SORT_KTH_CMD                      {913, 1}
#define SORT_ID_DEL_MIN_SORTCNT_EN                {912, 1}
#define SORT_ID_DES_DLY_NUM_SW                    {911, 1}
#define SORT_ID_DES_DLY_NUM_AUTO                  {910, 1}
#define SORT_ID_RESERVED14                        {906, 4}
#define SORT_ID_SORT_AUTO_INDX                    {905, 1}
#define SORT_ID_SORT_INDX_EN                      {904, 1}
#define SORT_ID_SORT_DESCEND_EN                   {903, 1}
#define SORT_ID_RESERVED15                        {902, 1}
#define SORT_ID_SORT_EN                           {901, 1}
#define SORT_ID_UNIQUE_EN                         {900, 1}
#define SORT_ID_CMP_CHAIN_NUM                     {898, 2}
#define SORT_ID_CMP_DATA_FMT                      {896, 2}
#define SORT_ID_SRC_DATA_ADDR                     {928, 32}
#define SORT_ID_DST_INDEX_ADDR_39_32              {984, 8}
#define SORT_ID_SRC_INDEX_ADDR_39_32              {976, 8}
#define SORT_ID_DST_DATA_ADDR_39_32               {968, 8}
#define SORT_ID_SRC_DATA_ADDR_39_32               {960, 8}
#define SORT_ID_DST_DATA_ADDR_31_0                {992, 32}
#define SORT_ID_VALUE_TOP_M                       {1024, 32}
#define SORT_ID_SRC_SIZE_DW                       {1056, 32}
#define SORT_ID_SRC_INDEX_ADDR_31_0               {1088, 32}
#define SORT_ID_DST_INDEX_ADDR_31_0               {1120, 32}


// sort pack defines
#define SORT_PACK_RESERVED0(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_INT_ENABLE(val)                 {SORT_ID_INT_ENABLE, (val)}
#define SORT_PACK_PIO_ENABLE(val)                 {SORT_ID_PIO_ENABLE, (val)}
#define SORT_PACK_DSCRP_START_ADDR_31_4(val)      {SORT_ID_DSCRP_START_ADDR_31_4, (val)}
#define SORT_PACK_RESERVED1(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_DSCRP_START(val)                {SORT_ID_DSCRP_START, (val)}
#define SORT_PACK_DSCRP_START_ADDR_63_32(val)     {SORT_ID_DSCRP_START_ADDR_63_32, (val)}
#define SORT_PACK_OP_SYNC_ID_FINISH(val)          {SORT_ID_OP_SYNC_ID_FINISH, (val)}
#define SORT_PACK_RESERVED2(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_ENGINE_BUSY(val)                {SORT_ID_ENGINE_BUSY, (val)}
#define SORT_PACK_RESERVED3(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_PIO_BUF_DEPTH(val)              {SORT_ID_PIO_BUF_DEPTH, (val)}
#define SORT_PACK_RESERVED4(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_DSCRP_INT_STS(val)              {SORT_ID_DSCRP_INT_STS, (val)}
#define SORT_PACK_RESERVED5(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_REG_SYNC_ID_SW_CLR(val)         {SORT_ID_REG_SYNC_ID_SW_CLR, (val)}
#define SORT_PACK_RESERVED6(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_REG_SYNC_ID_31_0(val)           {SORT_ID_REG_SYNC_ID_31_0, (val)}
#define SORT_PACK_REG_SYNC_ID_63_32(val)          {SORT_ID_REG_SYNC_ID_63_32, (val)}
#define SORT_PACK_REG_SYNC_ID_95_64(val)          {SORT_ID_REG_SYNC_ID_95_64, (val)}
#define SORT_PACK_REG_SYNC_ID_127_96(val)         {SORT_ID_REG_SYNC_ID_127_96, (val)}
#define SORT_PACK_REG_SYNC_ID_159_128(val)        {SORT_ID_REG_SYNC_ID_159_128, (val)}
#define SORT_PACK_REG_SYNC_ID_191_160(val)        {SORT_ID_REG_SYNC_ID_191_160, (val)}
#define SORT_PACK_REG_SYNC_ID_223_192(val)        {SORT_ID_REG_SYNC_ID_223_192, (val)}
#define SORT_PACK_REG_SYNC_ID_255_224(val)        {SORT_ID_REG_SYNC_ID_255_224, (val)}
#define SORT_PACK_RESERVED7(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_EOD(val)                        {SORT_ID_EOD, (val)}
#define SORT_PACK_RESERVED8(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_INT_STS_EN(val)                 {SORT_ID_INT_STS_EN, (val)}
#define SORT_PACK_RESERVED9(val)                  {SORT_ID_RESERVED, (val)}
#define SORT_PACK_ENABLE_SYNCID(val)              {SORT_ID_ENABLE_SYNCID, (val)}
#define SORT_PACK_RESERVED10(val)                 {SORT_ID_RESERVED, (val)}
#define SORT_PACK_DSCP_VLD(val)                   {SORT_ID_DSCP_VLD, (val)}
#define SORT_PACK_OP_SYNC_ID(val)                 {SORT_ID_OP_SYNC_ID, (val)}
#define SORT_PACK_EXP_SYNC_ID_0(val)              {SORT_ID_EXP_SYNC_ID_0, (val)}
#define SORT_PACK_EXP_SYNC_ID_1(val)              {SORT_ID_EXP_SYNC_ID_1, (val)}
#define SORT_PACK_EXP_SYNC_ID_2(val)              {SORT_ID_EXP_SYNC_ID_2, (val)}
#define SORT_PACK_EXP_SYNC_ID_3(val)              {SORT_ID_EXP_SYNC_ID_3, (val)}
#define SORT_PACK_EXP_SYNC_ID_4(val)              {SORT_ID_EXP_SYNC_ID_4, (val)}
#define SORT_PACK_EXP_SYNC_ID_5(val)              {SORT_ID_EXP_SYNC_ID_5, (val)}
#define SORT_PACK_EXP_SYNC_ID_6(val)              {SORT_ID_EXP_SYNC_ID_6, (val)}
#define SORT_PACK_EXP_SYNC_ID_7(val)              {SORT_ID_EXP_SYNC_ID_7, (val)}
#define SORT_PACK_SRC_OFFSET_INDX(val)            {SORT_ID_SRC_OFFSET_INDX, (val)}
#define SORT_PACK_SORTCNT_ADDR_31_0(val)          {SORT_ID_SORTCNT_ADDR_31_0, (val)}
#define SORT_PACK_SORTCNT_ADDR_39_32(val)         {SORT_ID_SORTCNT_ADDR_39_32, (val)}
#define SORT_PACK_DIS_WR_DST_SORTCNT(val)         {SORT_ID_DIS_WR_DST_SORTCNT, (val)}
#define SORT_PACK_DIS_WR_DST_SORT_DAT(val)        {SORT_ID_DIS_WR_DST_SORT_DAT, (val)}
#define SORT_PACK_DIS_WR_DST_SORT_IDX(val)        {SORT_ID_DIS_WR_DST_SORT_IDX, (val)}
#define SORT_PACK_SORT_RES_INDX_SEL(val)          {SORT_ID_SORT_RES_INDX_SEL, (val)}
#define SORT_PACK_RESERVED12(val)                 {SORT_ID_RESERVED, (val)}
#define SORT_PACK_RESERVED13(val)                 {SORT_ID_RESERVED, (val)}
#define SORT_PACK_SORT_KTH_CMD(val)               {SORT_ID_SORT_KTH_CMD, (val)}
#define SORT_PACK_DEL_MIN_SORTCNT_EN(val)         {SORT_ID_DEL_MIN_SORTCNT_EN, (val)}
#define SORT_PACK_DES_DLY_NUM_SW(val)             {SORT_ID_DES_DLY_NUM_SW, (val)}
#define SORT_PACK_DES_DLY_NUM_AUTO(val)           {SORT_ID_DES_DLY_NUM_AUTO, (val)}
#define SORT_PACK_RESERVED14(val)                 {SORT_ID_RESERVED, (val)}
#define SORT_PACK_SORT_AUTO_INDX(val)             {SORT_ID_SORT_AUTO_INDX, (val)}
#define SORT_PACK_SORT_INDX_EN(val)               {SORT_ID_SORT_INDX_EN, (val)}
#define SORT_PACK_SORT_DESCEND_EN(val)            {SORT_ID_SORT_DESCEND_EN, (val)}
#define SORT_PACK_RESERVED15(val)                 {SORT_ID_RESERVED, (val)}
#define SORT_PACK_SORT_EN(val)                    {SORT_ID_SORT_EN, (val)}
#define SORT_PACK_UNIQUE_EN(val)                  {SORT_ID_UNIQUE_EN, (val)}
#define SORT_PACK_CMP_CHAIN_NUM(val)              {SORT_ID_CMP_CHAIN_NUM, (val)}
#define SORT_PACK_CMP_DATA_FMT(val)               {SORT_ID_CMP_DATA_FMT, (val)}
#define SORT_PACK_SRC_DATA_ADDR(val)              {SORT_ID_SRC_DATA_ADDR, (val)}
#define SORT_PACK_DST_INDEX_ADDR_39_32(val)       {SORT_ID_DST_INDEX_ADDR_39_32, (val)}
#define SORT_PACK_SRC_INDEX_ADDR_39_32(val)       {SORT_ID_SRC_INDEX_ADDR_39_32, (val)}
#define SORT_PACK_DST_DATA_ADDR_39_32(val)        {SORT_ID_DST_DATA_ADDR_39_32, (val)}
#define SORT_PACK_SRC_DATA_ADDR_39_32(val)        {SORT_ID_SRC_DATA_ADDR_39_32, (val)}
#define SORT_PACK_DST_DATA_ADDR_31_0(val)         {SORT_ID_DST_DATA_ADDR_31_0, (val)}
#define SORT_PACK_VALUE_TOP_M(val)                {SORT_ID_VALUE_TOP_M, (val)}
#define SORT_PACK_SRC_SIZE_DW(val)                {SORT_ID_SRC_SIZE_DW, (val)}
#define SORT_PACK_SRC_INDEX_ADDR_31_0(val)        {SORT_ID_SRC_INDEX_ADDR_31_0, (val)}
#define SORT_PACK_DST_INDEX_ADDR_31_0(val)        {SORT_ID_DST_INDEX_ADDR_31_0, (val)}


#endif  // __SORT_REG_DEF_H__
