if(USING_RTTHREAD)
    set(CMAKE_SYSROOT $ENV{RTTHREAD_TOOLCHAIN}/sysroot)
    set(CMAKE_C_COMPILER $ENV{RTTHREAD_TOOLCHAIN}/bin/riscv64-unknown-linux-musl-gcc)
    set(CMAKE_ASM_COMPILER $ENV{RTTHREAD_TOOLCHAIN}/bin/riscv64-unknown-linux-musl-gcc)
    set(CMAKE_CXX_COMPILER $ENV{RTTHREAD_TOOLCHAIN}/bin/riscv64-unknown-linux-musl-g++)
else()
    set(CMAKE_C_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-gcc)
    set(CMAKE_ASM_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER $ENV{RISCV_TOOLCHAIN}/bin/riscv64-unknown-linux-gnu-g++)
endif()
